### ISSUE TITLE
Authentication issue when plugin in app_plugins folder

### ISSUE THREAD

**Issue by MrLeeAustin** [Nicholas-Westby/usergrouppermissions#6]
In Umbraco 7.2.2 and onwards when the plugin is in the app_plugins folder Umbraco can't authenticate and so never loads the dialog.

See this issues:

http://issues.umbraco.org/issue/U4-6352

I found by moving it to the Unbraco/Plugins folder and changing the source to reflect that it works perfectly.

**Comment by Nicholas-Westby** [comment]
Strange. I haven't encountered that issue and I've been developing this on the latest versions of Umbraco (7.2.6, 7.2.7, and 7.2.8). Can you send a screenshot that shows the HTTP request failing and any details related to that (e.g., request headers, response code, response body).

Also, that issue is talking about routes, and the only routes I'm using are in /umbraco/backoffice/ (the views reside in App_Plugins, but that's not what the issue is if I understand it correctly).

**Comment by Nicholas-Westby** [comment]
I am able to reproduce this. Looking into.

**Comment by Nicholas-Westby** [comment]
So, this problem occurs on 7.2.2, but it does not occur on 7.2.6 or 7.2.8. Not sure exactly what's causing it or when it was fixed, but perhaps I can get around this issue by using an HTML dialog rather than an ASPX dialog.

**Comment by Nicholas-Westby** [comment]
Thanks for the report. This has been fixed. The get the fix, install version 1.1.0: https://our.umbraco.org/projects/backoffice-extensions/user-group-permissions/
